all:
  vars:
    ansible_user: "$User_Name"
    ansible_ssh_private_key_file: "$Key_Path"
    ansible_become_pass: "$User_Password"
  children:
    master_leader:
      hosts:
        master-001:
          ansible_host: "$IP_Address"
    master_other:
      hosts:
        master-002:
          ansible_host: "$IP_Address"
        master-003:
          ansible_host: "$IP_Address"
    worker:
      hosts:
        worker-001:
          ansible_host: "$IP_Address"
        worker-002:
          ansible_host: "$IP_Address"
