all:
  vars:
    ansible_user: $UserName
    ansible_ssh_private_key_file: $KeyPath
    ansible_become_pass: $UserPassword
  children:
    master_leader:
      hosts:
        $hostname-master-001:
          ansible_host: $IpAddress
    master_other:
      hosts:
        $hostname-master-002:
          ansible_host: $IpAddress
        $hostname-master-003:
          ansible_host: $IpAddress
    worker:
      hosts:
        $hostname-worker-001:
          ansible_host: $IpAddress
        $hostname-worker-002:
          ansible_host: $IpAddress
