all:
  vars:
    ansible_user: $UserName
    ansible_ssh_private_key_file: $KeyPath
    ansible_become_pass: $UserPassword
  children:
    master_leader:
      hosts:
        master-001:
          ansible_host: $IpAddress
    master_other:
      hosts:
        master-002:
          ansible_host: $IpAddress
        master-003:
          ansible_host: $IpAddress
    worker:
      hosts:
        worker-001:
          ansible_host: $IpAddress
        worker-002:
          ansible_host: $IpAddress
