- name: Initialize Docker Swarm on leader
  hosts: master_leader
  gather_facts: true

  vars:
    pod_network_cidr: "10.0.0.0/16"

  tasks:
    - name: Primary IP Address
      set_fact:
        leader_primary_ip: "{{ ansible_facts['default_ipv4']['address'] }}"

    - name: Check if Docker Swarm is already initialized
      shell: docker info --format '{{ "{{.Swarm.LocalNodeState}}" }}'
      register: swarm_status
      changed_when: false

    - name: Initialize Docker Swarm
      shell: docker swarm init --default-addr-pool "{{ pod_network_cidr }}" --advertise-addr "{{ leader_primary_ip }}"
      register: swarm_init
      when: swarm_status.stdout != 'active'

- name: Output Nodes
  hosts: master_leader
  gather_facts: true
  become: false
  tasks:
    - name: Wait for nodes to become ready
      pause:
        seconds: 60

    - name: Get all nodes
      shell: docker node ls
      register: docker_nodes_output
      changed_when: false

    - name: Display docker output
      debug:
        var: docker_nodes_output.stdout_lines
